sylius_fixtures:
    suites:
        default_geo:
            listeners:
                logger: ~
            fixtures:
                geographical:
                    options:
                        zones:
                            TH-CENTRAL:
                                name: "ภาคกลาง"
                                provinces:
                                    - "กรุงเทพมหานคร"
                            TH-NORTHEAST:
                                name: "อีสาน"
                                provinces:
                                    - "ขอนแก่น"
                        provinces:
                            TH: ~
        geo:
            listeners:
                logger: ~
            fixtures:
                geographical:
                    options:
                        zones:
                            TH-CENTRAL:
                                name: "ภาคกลาง"
                                provinces:
                                    - "กรุงเทพมหานคร"
                            TH-NORTHEAST:
                                name: "อีสาน"
                                provinces:
                                    - "ขอนแก่น"
                        provinces:
                            TH:
                                "กรุงเทพมหานคร":
                                    "คลองเตย":
                                        - "คลองเตย, 10110"
                                        - "คลองตัน, 10110"
                                        - "พระโขนง, 10110"
                                    "คลองสาน":
                                        - "คลองต้นไทร"
                                        - "คลองสาน"
                                        - "บางลำภูล่าง"
                                        - "สมเด็จเจ้าพระยา"
                                    "คลองสามวา":
                                        - "ทรายกองดิน"
                                        - "ทรายกองดินใต้"
                                        - "บางชัน"
                                        - "สามวาตะวันตก"
                                        - "สามวาตะวันออก"
                                    "คันนายาว":
                                        - "คันนายาว"
                                    "จตุจักร":
                                        - "จตุจักร"
                                        - "จอมพล"
                                        - "จันทรเกษม"
                                        - "ลาดยาว"
                                        - "เสนานิคม"
                                    "จอมทอง":
                                        - "จอมทอง"
                                        - "บางขุนเทียน"
                                        - "บางค้อ"
                                        - "บางมด"
                                    "ดอนเมือง":
                                        - "สีกัน"
                                    "ดินแดง":
                                        - "ดินแดง"
                                    "ดุสิต":
                                        - "ดุสิต"
                                        - "ถนนนครไชยศรี"
                                        - "วชิรพยาบาล"
                                        - "สวนจิตรลดา"
                                        - "สี่แยกมหานาค"
                                    "ตลิ่งชัน":
                                        - "ตลิ่งชัน"
                                        - "คลองชักพระ"
                                        - "ฉิมพลี"
                                        - "บางเชือกหนัง"
                                        - "บางพรม"
                                        - "บางระมาด"
                                    "ทวีวัฒนา":
                                        - "ทวีวัฒนา"
                                        - "ศาลาธรรมสพน์"
                                    "ทุ่งครุ":
                                        - "ทุ่งครุ"
                                        - "บางมด"
                                    "ธนบุรี":
                                        - "ดาวคะนอง"
                                        - "ตลาดพลู"
                                        - "บางยี่เรือ"
                                        - "บุคคโล"
                                        - "วัดกัลยาณ์"
                                        - "สำเหร่"
                                        - "หิรัญรูจี"
                                    "บางเขน":
                                        - "ท่าแร้ง"
                                        - "อนุสาวรีย์"
                                    "บางแค":
                                        - "บางแค"
                                        - "บางแคเหนือ"
                                        - "บางไผ่"
                                        - "หลักสอง"
                                    "บางกอกใหญ่":
                                        - "วัดท่าพระ"
                                        - "วัดอรุณ"
                                    "บางกอกน้อย":
                                        - "บางขุนนนท์"
                                        - "บางขุนศรี"
                                        - "บ้านช่างหล่อ"
                                        - "ศิริราช"
                                        - "อรุณอมรินทร์"
                                    "บางกะปิ":
                                        - "คลองจั่น"
                                        - "หัวหมาก"
                                    "บางขุนเทียน":
                                        - "ท่าข้าม"
                                        - "แสมดำ"
                                    "บางคอแหลม":
                                        - "บางโคล่"
                                        - "บางคอแหลม"
                                        - "วัดพระยาไกร"
                                    "บางซื่อ":
                                        - "บางซื่อ"
                                    "บางนา":
                                        - "บางนา"
                                    "บางบอน":
                                        - "บางบอน"
                                    "บางพลัด":
                                        - "บางพลัด"
                                        - "บางบำหรุ"
                                        - "บางยี่ขัน"
                                        - "บางอ้อ"
                                    "บางรัก":
                                        - "บางรัก"
                                        - "มหาพฤฒาราม"
                                        - "สี่พระยา"
                                        - "สีลม"
                                        - "สุริยวงศ์"
                                    "บึงกุ่ม":
                                        - "คลองกุ่ม"
                                    "ปทุมวัน":
                                        - "ปทุมวัน"
                                        - "รองเมือง"
                                        - "ลุมพินี"
                                        - "วังใหม่"
                                    "ประเวศ":
                                        - "ประเวศ"
                                        - "ดอกไม้"
                                        - "หนองบอน"
                                    "ป้อมปราบศัตรูพ่าย":
                                        - "คลองมหานาค"
                                        - "บ้านบาตร"
                                        - "ป้อมปราบ"
                                        - "วัดเทพศิรินทร์"
                                        - "วัดโสมนัส"
                                    "พญาไท":
                                        - "สามเสนใน"
                                    "พระโขนง":
                                        - "บางจาก"
                                    "พระนคร":
                                        - "ชนะสงคราม"
                                        - "ตลาดยอด"
                                        - "บวรนิเวศ"
                                        - "บางขุนพรหม"
                                        - "บ้านพานถม"
                                        - "พระบรมมหาราชวัง"
                                        - "วังบูรพาภิรมย์"
                                        - "วัดราชบพิธ"
                                        - "วัดสามพระยา"
                                        - "ศาลเจ้าพ่อเสือ"
                                        - "สำราญราษฎร์"
                                        - "เสาชิงช้า"
                                    "ภาษีเจริญ":
                                        - "คลองขวาง"
                                        - "คูหาสวรรค์"
                                        - "บางจาก"
                                        - "บางด้วน"
                                        - "บางแวก"
                                        - "บางหว้า"
                                        - "ปากคลองภาษีเจริญ"
                                    "มีนบุรี":
                                        - "มีนบุรี"
                                        - "แสนแสบ"
                                    "ยานนาวา":
                                        - "ช่องนนทรี"
                                        - "บางโพงพาง"
                                    "ราชเทวี":
                                        - "ถนนเพชรบุรี"
                                        - "ถนนพญาไท"
                                        - "ทุ่งพญาไท"
                                        - "มักกะสัน"
                                    "ราษฎร์บูรณะ":
                                        - "บางปะกอก"
                                        - "ราษฎร์บูรณะ"
                                    "ลาดกระบัง":
                                        - "ขุมทอง"
                                        - "คลองสองต้นนุ่น"
                                        - "คลองสามประเวศ"
                                        - "ทับยาว"
                                        - "ลาดกระบัง"
                                        - "ลำปลาทิว"
                                    "ลาดพร้าว":
                                        - "ลาดพร้าว"
                                        - "จรเข้บัว"
                                    "วังทองหลาง":
                                        - "วังทองหลาง"
                                    "วัฒนา":
                                        - "คลองเตยเหนือ"
                                        - "คลองตันเหนือ"
                                        - "พระโขนงเหนือ"
                                    "สวนหลวง":
                                        - "สวนหลวง"
                                    "สะพานสูง":
                                        - "สะพานสูง"
                                    "สัมพันธวงศ์":
                                        - "สัมพันธวงศ์"
                                        - "จักรวรรดิ"
                                        - "ตลาดน้อย"
                                    "สาทร":
                                        - "ทุ่งมหาเมฆ"
                                        - "ทุ่งวัดดอน"
                                        - "ยานนาวา"
                                    "สายไหม":
                                        - "คลองถนน"
                                        - "สายไหม"
                                        - "ออเงิน"
                                    "หนองแขม":
                                        - "หนองแขม"
                                        - "หนองค้างพลู"
                                    "หนองจอก":
                                        - "หนองจอก"
                                        - "กระทุ่มราย"
                                        - "คลองสิบ"
                                        - "คลองสิบสอง"
                                        - "คู้ฝั่งเหนือ"
                                        - "โคกแฝด"
                                        - "ลำต้อยติ่ง"
                                        - "ลำผักชี"
                                    "หลักสี่":
                                        - "ตลาดบางเขน"
                                        - "ทุ่งสองห้อง"
                                    "ห้วยขวาง":
                                        - "ห้วยขวาง"
                                        - "บางกะปิ"
                                        - "สามเสนนอก"
                                "ขอนแก่น": ~
                                "สมุทรปราการ": ~
                                "นนทบุรี": ~
                                "ปทุมธานี": ~
                                "พระนครศรีอยุธยา": ~
                                "อ่างทอง": ~
                                "ลพบุรี": ~
                                "สิงห์บุรี": ~
                                "ชัยนาท": ~
                                "สระบุรี": ~
                                "ชลบุรี": ~
                                "ระยอง": ~
                                "จันทบุรี": ~
                                "ตราด": ~
                                "ฉะเชิงเทรา": ~
                                "ปราจีนบุรี": ~
                                "นครนายก": ~
                                "สระแก้ว": ~
                                "นครราชสีมา": ~
                                "บุรีรัมย์": ~
                                "สุรินทร์": ~
                                "ศรีสะเกษ": ~
                                "อุบลราชธานี": ~
                                "ยโสธร": ~
                                "ชัยภูมิ": ~
                                "อำนาจเจริญ": ~
                                "หนองบัวลำภู": ~
                                "อุดรธานี": ~
                                "เลย": ~
                                "หนองคาย": ~
                                "มหาสารคาม": ~
                                "ร้อยเอ็ด": ~
                                "กาฬสินธุ์": ~
                                "สกลนคร": ~
                                "นครพนม": ~
                                "มุกดาหาร": ~
                                "เชียงใหม่": ~
                                "ลำพูน": ~
                                "ลำปาง": ~
                                "อุตรดิตถ์": ~
                                "แพร่": ~
                                "น่าน": ~
                                "พะเยา": ~
                                "เชียงราย": ~
                                "แม่ฮ่องสอน": ~
                                "นครสวรรค์": ~
                                "อุทัยธานี": ~
                                "กำแพงเพชร": ~
                                "ตาก": ~
                                "สุโขทัย": ~
                                "พิษณุโลก": ~
                                "พิจิตร": ~
                                "เพชรบูรณ์": ~
                                "ราชบุรี": ~
                                "กาญจนบุรี": ~
                                "สุพรรณบุรี": ~
                                "นครปฐม": ~
                                "สมุทรสาคร": ~
                                "สมุทรสงคราม": ~
                                "เพชรบุรี": ~
                                "ประจวบคีรีขันธ์": ~
                                "นครศรีธรรมราช": ~
                                "กระบี่": ~
                                "พังงา": ~
                                "ภูเก็ต": ~
                                "สุราษฎร์ธานี": ~
                                "ระนอง": ~
                                "ชุมพร": ~
                                "สงขลา": ~
                                "สตูล": ~
                                "ตรัง": ~
                                "พัทลุง": ~
                                "ปัตตานี": ~
                                "ยะลา": ~
                                "นราธิวาส": ~
                                "บึงกาฬ": ~
